ROSc: include/rosc/com/xmlrpc.h File Reference
xmlrpc.h File Reference
#include <rosc/system/eth.h>
#include <rosc/sebs_parse_fw/send_modules/socket_connect.h>
#include <rosc/sebs_parse_fw/sebs_parser_frame.h>
#include <rosc/sebs_parse_fw/adv_modules/sebs_parse_http.h>
#include <rosc/sebs_parse_fw/adv_modules/sebs_parse_xml.h>
#include <rosc/sebs_parse_fw/std_modules/sebs_parse_copy2buffer.h>
#include <rosc/sebs_parse_fw/std_modules/sebs_parse_parseurl.h>
#include <rosc/sebs_parse_fw/std_modules/sebs_parse_numberparse.h>
#include <rosc/sebs_parse_fw/std_modules/sebs_parse_seekstring.h>
#include <rosc/sebs_parse_fw/send_modules/msggen.h>
#include <rosc/system/status.h>
#include <rosc/com/ros_handler.h>
Data Structures
struct xmlrpc_data_t
Macros
#define XMLRPC_MAX_ARRAY_NESTING 3
#define XMLRPC_SECURITY_MAX_MESSAGE_SIZE 1024
Enumerations
enum xmlrpc_t { XMLRPC_TYPE_CLIENT, XMLRPC_TYPE_SERVER }
enum xmlrpc_state_t {
XMLRPC_STATE_SENDING_REQUEST, XMLRPC_STATE_SENDING_RESPONSE, XMLRPC_STATE_CLOSE, XMLRPC_STATE_CONNECT,
XMLRPC_STATE_SEND_REQUEST, XMLRPC_STATE_HTTP, XMLRPC_STATE_XML, XMLRPC_STATE_SEND_RESPONSE,
XMLRPC_STATE_SUBSCRIBER_RECONNECT, XMLRPC_STATE_SUBSCRIBER_WAITING_FOR_RECONNECT, XMLRPC_SERVE_TOPIC_REQUEST
}
enum xmlrpc_header_descriptors_t { XMLRPC_DESCRIPTOR_UNKNOWN =SEBS_PARSE_SEEKSTRING_NOT_FOUND }
enum xmlrpc_http_actions_t { XMLRPC_ACTION_UNKNOWN =SEBS_PARSE_SEEKSTRING_NOT_FOUND }
enum xmlrpc_http_methods_t { XMLRPC_METHOD_UNKNOWN =SEBS_PARSE_SEEKSTRING_NOT_FOUND }
enum parse_xmlrpc_tags_t { XMLRPC_TAG_NONE_UNKNOWN = SEBS_PARSE_SEEKSTRING_NOT_FOUND, XMLRPC_TAG_STRINGS =(XMLRPC) }
enum parse_xmlrpc_attrib_t { XMLRPC_ATTRIBUTE_NONE_UNKNOWN = SEBS_PARSE_SEEKSTRING_NOT_FOUND }
enum xmlrpc_result_handling_t {
XMLRPC_RESULT_NONE, XMLRPC_RESULT_REQUEST_SENT, XMLRPC_RESULT_CONTENT_LENGTH, XMLRPC_RESULT_METHOD_NAME,
XMLRPC_RESULT_CALLERID, XMLRPC_RESULT_PUBLISHER_UPDATE_URL, XMLRPC_RESULT_FIND_TOPIC, XMLRPC_RESULT_REQUEST_TOPIC_PORT,
XMLRPC_RESULT_ACKNOWLEDGE
}
enum xmlrpc_ros_methodname_t { XMLRPC_METHODNAME_UNKNOWN =SEBS_PARSE_SEEKSTRING_NOT_FOUND, XMLRPC_SLAVE_METHODNAMES =(XMLRPC) }
enum xmlrpc_tag_state_t {
XMLRPC_TAG_STATE_NONE, XMLRPC_TAG_STATE_METHODRC, XMLRPC_TAG_STATE_PARAMS, XMLRPC_TAG_STATE_PARAM,
XMLRPC_TAG_STATE_VALUE
}
enum xmlrpc_type_tag_t {
XMLRPC_TYPE_TAG_NONE, XMLRPC_TYPE_TAG_BOOLEAN, XMLRPC_TYPE_TAG_STRING, XMLRPC_TYPE_TAG_INT,
XMLRPC_TYPE_TAG_DOUBLE
}
enum xmlrpc_array_state_t { XMLRPC_ARRAY_STATE_NONE, XMLRPC_ARRAY_STATE_ARRAY, XMLRPC_ARRAY_STATE_DATA, XMLRPC_ARRAY_STATE_VALUE }
enum xmlrpc_client_type_t { XMLRPC_CLIENT_TYPE_NO_CLIENT, XMLRPC_CLIENT_TYPE_REGISTER, XMLRPC_CLIENT_TYPE_UNREGISTER, XMLRPC_CLIENT_TYPE_REQUEST_TOPIC }
Functions
sebs_parse_return_t xmlrpc (sebs_parser_data_t *pdata)
Macro Definition Documentation
#define XMLRPC_MAX_ARRAY_NESTING 3
Definition at line 35 of file xmlrpc.h.
Referenced by xmlrpc().
#define XMLRPC_SECURITY_MAX_MESSAGE_SIZE 1024
Definition at line 37 of file xmlrpc.h.
Referenced by xmlrpc().
Enumeration Type Documentation
enum parse_xmlrpc_attrib_t
XML Attributes
Enumerator
XMLRPC_ATTRIBUTE_NONE_UNKNOWN
imports all string numbers from autogenerated file
Definition at line 119 of file xmlrpc.h.
enum parse_xmlrpc_tags_t
XML Tags This enum contains the number for each known tag
Enumerator
XMLRPC_TAG_NONE_UNKNOWN
ROSC_XMLRPC_TAG_NONE_UNKNOWN.
XMLRPC_TAG_STRINGS
imports all string numbers from autogenerated file
__XMLRPC_TAG_STRINGS
Definition at line 109 of file xmlrpc.h.
enum xmlrpc_array_state_t
Enumerator
XMLRPC_ARRAY_STATE_NONE
XMLRPC_ARRAY_STATE_ARRAY
XMLRPC_ARRAY_STATE_DATA
XMLRPC_ARRAY_STATE_VALUE
Definition at line 164 of file xmlrpc.h.
enum xmlrpc_client_type_t
Enumerator
XMLRPC_CLIENT_TYPE_NO_CLIENT
XMLRPC_CLIENT_TYPE_REGISTER
XMLRPC_CLIENT_TYPE_UNREGISTER
XMLRPC_CLIENT_TYPE_REQUEST_TOPIC
Definition at line 174 of file xmlrpc.h.
enum xmlrpc_header_descriptors_t
Creating the enum for descriptor usage by hander function
Enumerator
XMLRPC_DESCRIPTOR_UNKNOWN
Definition at line 80 of file xmlrpc.h.
enum xmlrpc_http_actions_t
Creating the enum for action usage by hander function
Enumerator
XMLRPC_ACTION_UNKNOWN
Definition at line 90 of file xmlrpc.h.
enum xmlrpc_http_methods_t
Creating the enum for method usage by hander function
Enumerator
XMLRPC_METHOD_UNKNOWN
Definition at line 99 of file xmlrpc.h.
enum xmlrpc_result_handling_t
Enumerator
XMLRPC_RESULT_NONE
XMLRPC_RESULT_REQUEST_SENT
XMLRPC_RESULT_CONTENT_LENGTH
XMLRPC_RESULT_METHOD_NAME
XMLRPC_RESULT_CALLERID
XMLRPC_RESULT_PUBLISHER_UPDATE_URL
XMLRPC_RESULT_FIND_TOPIC
XMLRPC_RESULT_REQUEST_TOPIC_PORT
XMLRPC_RESULT_ACKNOWLEDGE
Definition at line 126 of file xmlrpc.h.
enum xmlrpc_ros_methodname_t
Enumerator
XMLRPC_METHODNAME_UNKNOWN
XMLRPC_SLAVE_METHODNAMES
Definition at line 139 of file xmlrpc.h.
enum xmlrpc_state_t
Enumerator
XMLRPC_STATE_SENDING_REQUEST
XMLRPC_STATE_SENDING_RESPONSE
XMLRPC_STATE_CLOSE
XMLRPC_STATE_CONNECT
XMLRPC_STATE_SEND_REQUEST
XMLRPC_STATE_HTTP
XMLRPC_STATE_XML
XMLRPC_STATE_SEND_RESPONSE
XMLRPC_STATE_SUBSCRIBER_RECONNECT
XMLRPC_STATE_SUBSCRIBER_WAITING_FOR_RECONNECT
XMLRPC_SERVE_TOPIC_REQUEST
Definition at line 62 of file xmlrpc.h.
enum xmlrpc_t
Enumerator
XMLRPC_TYPE_CLIENT
XMLRPC_TYPE_SERVER
Definition at line 54 of file xmlrpc.h.
enum xmlrpc_tag_state_t
Enumerator
XMLRPC_TAG_STATE_NONE
XMLRPC_TAG_STATE_METHODRC
XMLRPC_TAG_STATE_PARAMS
XMLRPC_TAG_STATE_PARAM
XMLRPC_TAG_STATE_VALUE
Definition at line 145 of file xmlrpc.h.
enum xmlrpc_type_tag_t
Enumerator
XMLRPC_TYPE_TAG_NONE
XMLRPC_TYPE_TAG_BOOLEAN
XMLRPC_TYPE_TAG_STRING
XMLRPC_TYPE_TAG_INT
XMLRPC_TYPE_TAG_DOUBLE
Definition at line 155 of file xmlrpc.h.
Function Documentation
sebs_parse_return_t xmlrpc (sebs_parser_data_t * pdata)
Definition at line 47 of file xmlrpc.c.
References __NODENAME_MAX_LEN__, xmlrpc_data_t::action, sebs_parser_data_t::additional_storage, xmlrpc_data_t::array_level, xmlrpc_data_t::array_state, xmlrpc_data_t::array_value_number, xmlrpc_data_t::caller_id, xmlrpc_data_t::client_type, xmlrpc_data_t::connect, CONNECT_DATA_STATE_URL, socket_t::connect_info, sebs_parser_data_t::connection_interface, xmlrpc_data_t::copy2buffer, socket_connect_info_t::data_state, DEBUG_PRINT, DEBUG_PRINT_STR, sebs_parse_xml_data_t::depth, sebs_parse_http_data_t::descriptor, sebs_parser_data_t::event, xmlrpc_data_t::gen, xmlrpc_data_t::genPayloadData, sebs_parser_data_t::handler_data, iface_t::handler_function, sebs_parser_data_t::handler_function, sebs_parser_data_t::handler_init, xmlrpc_data_t::http, http_header_stdtext, xmlrpc_data_t::http_response_code, socket_t::iface, xmlrpc_data_t::iface, iface_listen(), ros_iface_init_t::iface_name, iface_t::init_data, sebs_parser_data_t::init_data, listen_socket_t::interface, interface_list_start, sebs_parse_numberparse_data_t::last_byte, sebs_parser_data_t::len, listen_socket_list_start, master_uri, xmlrpc_data_t::method, MSGGEN_TYPE_HTTP_ERROR, MSGGEN_TYPE_XMLRPC_ACK, MSGGEN_TYPE_XMLRPC_ERROR, MSGGEN_TYPE_XMLRPC_REQ_REGISTER_PUBLISHER, MSGGEN_TYPE_XMLRPC_REQ_REGISTER_SUBSCRIBER, MSGGEN_TYPE_XMLRPC_REQ_UNREGISTER_PUBLISHER, MSGGEN_TYPE_XMLRPC_REQ_UNREGISTER_SUBSCRIBER, MSGGEN_TYPE_XMLRPC_REQUEST_TOPIC, MSGGEN_TYPE_XMLRPC_RESPOND_REQUEST_TOPIC, iface_t::next, socket_t::next, listen_socket_t::next, sebs_parse_numberparse_data_t::number, sebs_parse_xml_data_t::numberparse, sebs_parse_http_data_t::numberparse, sebs_parser_data_t::out_len, sebs_parser_data_t::overall_len, xmlrpc_data_t::param_no, socket_t::pdata, listen_socket_t::port, socket_connect_info_t::remote_port, sebs_parse_seekstring_data_t::result, sebs_parse_numberparse_data_t::result, xmlrpc_data_t::result_handling, ros_handler(), ROS_HANDLER_TYPE_TOPIC_PUBLISHER, ROS_HANDLER_TYPE_TOPIC_SUBSCRIBER, rosc_static_socket_additional_data_size, ROSC_STRCPY, xmlrpc_data_t::rpc_methodname, SEBS_PARSE_COPY2BUFFER_INIT, SEBS_PARSE_EVENT_HANDLER_CALL_FUNCTION_END, SEBS_PARSE_EVENT_LEN_EQUAL_SMALLER_ZERO, SEBS_PARSE_EVENT_MESSAGE_SECURITY_OVER_SIZE, SEBS_PARSE_HTTP_EVENT_ACTION_PARSED, SEBS_PARSE_HTTP_EVENT_CONTENT_TYPE, SEBS_PARSE_HTTP_EVENT_ERROR_ACTION_NOT_FOUND, SEBS_PARSE_HTTP_EVENT_ERROR_BAD_REQUEST, SEBS_PARSE_HTTP_EVENT_ERROR_BAD_RESPONSE, SEBS_PARSE_HTTP_EVENT_ERROR_CONTENT_ENCODING, SEBS_PARSE_HTTP_EVENT_ERROR_CONTENT_LENGTH, SEBS_PARSE_HTTP_EVENT_ERROR_CONTENT_LENGTH_TOO_LONG, SEBS_PARSE_HTTP_EVENT_ERROR_METHOD_NOT_ALLOWED, SEBS_PARSE_HTTP_EVENT_ERROR_VERSION_NOT_SUPPORTED, SEBS_PARSE_HTTP_EVENT_HEADER_CONTENT, SEBS_PARSE_HTTP_EVENT_HEADER_END, SEBS_PARSE_HTTP_EVENT_METHOD_PARSED, SEBS_PARSE_HTTP_EVENT_RESPONSE_CODE, SEBS_PARSE_HTTP_INIT, SEBS_PARSE_HTTP_REQUEST_INIT, SEBS_PARSE_HTTP_RESPONSE_INIT, SEBS_PARSE_MSG_GEN, SEBS_PARSE_NUMBERPARSE_ANOTHER_CHAR, SEBS_PARSE_NUMBERPARSE_INIT, SEBS_PARSE_RETURN_GO_AHEAD, SEBS_PARSE_SEEKSTRING_INIT, SEBS_PARSE_XML_EVENT_ATTRIBUTE_APOSTROPHE, SEBS_PARSE_XML_EVENT_ATTRIBUTE_QUOTES, SEBS_PARSE_XML_EVENT_CDATA, SEBS_PARSE_XML_EVENT_CONTENT_START, SEBS_PARSE_XML_EVENT_ERROR_DEPTH, SEBS_PARSE_XML_EVENT_ERROR_MALFORMED, SEBS_PARSE_XML_EVENT_HANDLER_CALLED_SUBMODE_FINISHED, SEBS_PARSE_XML_EVENT_INSIDE_TAG, SEBS_PARSE_XML_EVENT_NONE, SEBS_PARSE_XML_EVENT_TAG, SEBS_PARSE_XML_INIT, SEBS_PARSE_XML_TAG_TYPE_CLOSE, sebs_parser_data_t::security_len, sebs_parse_xml_data_t::seekstring, sebs_parse_http_data_t::seekstring, sebs_parser_data_t::sending, SOCKET_CONNECT_INIT, socket_list_start, SOCKET_SIG_CLOSE, SOCKET_SIG_CONNECT, SOCKET_SIG_CONNECTED, SOCKET_SIG_COULD_NOT_CONNECT, SOCKET_SIG_COULD_NOT_RESOLVE_HOST, SOCKET_SIG_DATA_SENT, SOCKET_SIG_NO_CONNECTION, SOCKET_SIG_NO_DATA, SOCKET_SIG_RELEASE, SOCKET_SIG_TIMEOUT, SOCKET_STATE_INACTIVE, SOCKET_STATE_NOT_CONNECTED, socket_t::state, xmlrpc_data_t::tag_state, sebs_parse_xml_data_t::tag_type, sebs_parse_xml_data_t::tags, xmlrpc_data_t::type_tag, socket_connect_info_t::url, xmlrpc_data_t::xml, xmlrpc_data_t::xml_length, xmlrpc(), XMLRPC_ARRAY_STATE_ARRAY, XMLRPC_ARRAY_STATE_DATA, XMLRPC_ARRAY_STATE_NONE, XMLRPC_ARRAY_STATE_VALUE, xmlrpc_attribute_strings, XMLRPC_CLIENT_TYPE_REGISTER, XMLRPC_CLIENT_TYPE_REQUEST_TOPIC, XMLRPC_CLIENT_TYPE_UNREGISTER, xmlrpc_http_actions, XMLRPC_HTTP_ACTIONS_LEN, xmlrpc_http_descriptors, XMLRPC_HTTP_DESCRIPTORS_LEN, xmlrpc_http_methods, XMLRPC_HTTP_METHODS_LEN, XMLRPC_MAX_ARRAY_NESTING, XMLRPC_METHOD_UNKNOWN, XMLRPC_METHODNAME_UNKNOWN, XMLRPC_RESULT_ACKNOWLEDGE, XMLRPC_RESULT_CALLERID, XMLRPC_RESULT_CONTENT_LENGTH, XMLRPC_RESULT_FIND_TOPIC, XMLRPC_RESULT_METHOD_NAME, XMLRPC_RESULT_NONE, XMLRPC_RESULT_PUBLISHER_UPDATE_URL, XMLRPC_RESULT_REQUEST_SENT, XMLRPC_RESULT_REQUEST_TOPIC_PORT, XMLRPC_SECURITY_MAX_MESSAGE_SIZE, xmlrpc_slave_methodnames, XMLRPC_SLAVE_METHODNAMES_LEN, xmlrpc_data_t::xmlrpc_state, XMLRPC_STATE_CLOSE, XMLRPC_STATE_CONNECT, XMLRPC_STATE_HTTP, XMLRPC_STATE_SUBSCRIBER_RECONNECT, XMLRPC_STATE_XML, XMLRPC_TAG_STATE_METHODRC, XMLRPC_TAG_STATE_NONE, XMLRPC_TAG_STATE_PARAM, XMLRPC_TAG_STATE_PARAMS, XMLRPC_TAG_STATE_VALUE, xmlrpc_tag_strings, XMLRPC_TAG_STRINGS_LEN, xmlrpc_data_t::xmlrpc_type, XMLRPC_TYPE_CLIENT, XMLRPC_TYPE_SERVER, XMLRPC_TYPE_TAG_BOOLEAN, XMLRPC_TYPE_TAG_DOUBLE, XMLRPC_TYPE_TAG_INT, XMLRPC_TYPE_TAG_NONE, and XMLRPC_TYPE_TAG_STRING.
Referenced by rosc_spin(), and xmlrpc().