ROSc: include/rosc/system/eth.h File Reference
eth.h File Reference
#include <rosc/system/setup.h>
#include <rosc/sebs_parse_fw/sebs_parser_frame.h>
#include <rosc/system/spec.h>
#include <rosc/com/ros_msg_common.h>
#include <rosc/system/status.h>
#include <rosc/debug/debug_out.h>
Data Structures
struct iface_t
struct socket_connect_info_t
struct socket_connect_data_t
struct lookup_table_entry_t
struct socket_t
struct listen_socket_t
Macros
#define ROSC_STATIC_LOOKUP_TABLE_HEAD(MIN_SIZE)
#define ROSC_STATIC_LOOKUP_TABLE_END
#define ROSC_STATIC_LOOKUP_ENTRY(HOSTNAME, IP) {#HOSTNAME, IP},
#define MASTER_URI_STATIC(URI)
#define MASTER_URI_STATIC_MEMRES(URI, MEMSIZE)
Typedefs
typedef uint8_t ip_address_t [4]
typedef uint8_t * ip_address_ptr
typedef int16_t port_id_t
typedef __SOCKET_ID_TYPE__ socket_id_t
typedef __SOCKET_ID_TYPE__ listen_socket_id_t
typedef uint16_t port_t
typedef struct iface_t iface_t
typedef struct
socket_connect_info_t socket_connect_info_t
typedef struct lookup_table_entry_t lookup_table_entry_t
typedef struct socket_t socket_t
typedef struct listen_socket_t listen_socket_t
Enumerations
enum iface_state_t {
IFACE_STATE_RPC_INTERFACE, IFACE_STATE_UNREGISTERED, IFACE_STATE_DO_REGISTER, IFACE_STATE_STATE_OPERATION_PENDING,
IFACE_STATE_REGISTERED, IFACE_STATE_DO_UNREGISTER
}
enum listen_socket_state_t { LISTEN_SOCKET_STATE_CLOSED, LISTEN_SOCKET_STATE_UNUSED, LISTEN_SOCKET_STATE_ACTIVE }
enum socket_state_t {
SOCKET_STATE_INACTIVE, SOCKET_STATE_SETUP, SOCKET_STATE_NOT_CONNECTED, SOCKET_STATE_WAITING_FOR_CONNECTION,
SOCKET_STATE_CONNECTED
}
enum connect_data_state_t { CONNECT_DATA_STATE_URL, CONNECT_DATA_STATE_RESOLVE, CONNECT_DATA_STATE_IPV4, CONNECT_DATA_STATE_ERROR }
enum socket_connect_state_t {
SOCKET_CONNECT_STATE_URL_SCHEME, SOCKET_CONNECT_STATE_URL_IPV4_HOSTNAME, SOCKET_CONNECT_STATE_URI_HOSTNAME, SOCKET_CONNECT_STATE_URL_IPV6,
SOCKET_CONNECT_STATE_URL_PORT, SOCKET_CONNECT_STATE_CONNECT, SOCKET_CONNECT_STATE_ERROR
}
enum send_result_t { SEND_RESULT_OK =0, SEND_RESULT_CONNECTION_CLOSE, SEND_RESULT_CONNECTION_ERROR, SEND_RESULT_CONNECTION_TIMEOUT }
enum socket_sig_t {
SOCKET_SIG_COULD_NOT_CONNECT =-9, SOCKET_SIG_COULD_NOT_RESOLVE_HOST =-8, SOCKET_SIG_RELEASE = -7, SOCKET_SIG_TIMEOUT = -6,
SOCKET_SIG_CONNECT = -5, SOCKET_SIG_NO_CONNECTION = -4, SOCKET_SIG_CONNECTED = -3, SOCKET_SIG_DATA_SENT = -2,
SOCKET_SIG_NO_DATA = -1, SOCKET_SIG_CLOSE = 0
}
Functions
bool iface_list_insert (iface_t *interface)
bool unregister_interface (iface_t *interface)
bool register_interface (iface_t *interface)
void rosc_lists_init ()
bool rosc_iface_listen (iface_t *iface, uint16_t port_number)
void receive_packet (socket_id_t socket_id, uint8_t *buffer, uint32_t size)
bool rosc_hostlist_resolve (const char *hostname, size_t size, ip_address_ptr ip)
void abstract_static_initHostname ()
bool abstract_resolveIP (const char *hostname, size_t size, ip_address_ptr ip)
socket_id_t abstract_start_listening_on_port (port_t *port)
bool abstract_stop_listening_on_port (socket_id_t socket_id)
socket_id_t abstract_connect_socket (ip_address_t ip, port_t port)
send_result_t abstract_send_packet (socket_id_t socket_id, uint8_t *buffer, uint32_t size)
int32_t recv_packet (socket_id_t socket_id, uint8_t *buffer, uint32_t size)
void abstract_close_socket (socket_id_t socket)
void abstract_ros_spin_routine ()
socket_id_t abstract_socket_accept (listen_socket_id_t socket_id)
bool abstract_get_hostname (char *hostname, size_t maxlength)
Variables
char hostname []
char node_name []
socket_t * socket_list_start
listen_socket_t * listen_socket_list_start
iface_t * interface_list_start
char *const master_uri
port_t xmlrpc_port
const size_t rosc_static_socket_additional_data_size
Macro Definition Documentation
#define MASTER_URI_STATIC (URI)
Value:
size_t master_uri_size=sizeof(URI)-1;\
                char * const master_uri=URI
Examples:
static_pubsub.c.
Definition at line 204 of file eth.h.
#define MASTER_URI_STATIC_MEMRES (URI, MEMSIZE)
Value:
size_t master_uri_size=MEMSIZE;\
                char __master_uri__mem[MEMSIZE+1]=URI;\
                char * const master_uri=&__master_uri__mem
Definition at line 208 of file eth.h.
#define ROSC_STATIC_LOOKUP_ENTRY (HOSTNAME, IP) {#HOSTNAME, IP},
Examples:
static_pubsub.c.
Definition at line 159 of file eth.h.
#define ROSC_STATIC_LOOKUP_TABLE_END
Value:
};\
lookup_table_entry_t* rosc_static_lookup_table=(&__rosc_static_lookup_table[0]);\
size_t rosc_static_lookup_table_size=sizeof(__rosc_static_lookup_table)/sizeof(lookup_table_entry_t);
Examples:
static_pubsub.c.
Definition at line 154 of file eth.h.
#define ROSC_STATIC_LOOKUP_TABLE_HEAD (MIN_SIZE)
Value:
lookup_table_entry_t __rosc_static_lookup_table[MIN_SIZE]=\
{\
Examples:
static_pubsub.c.
Definition at line 150 of file eth.h.
Typedef Documentation
typedef struct iface_t iface_t
This is the definition of the struct containing various information for an interface
typedef uint8_t* ip_address_ptr
Definition at line 43 of file eth.h.
typedef uint8_t ip_address_t[4]
Definition at line 42 of file eth.h.
typedef __SOCKET_ID_TYPE__ listen_socket_id_t
Definition at line 47 of file eth.h.
typedef struct listen_socket_t listen_socket_t
typedef struct lookup_table_entry_t lookup_table_entry_t
typedef int16_t port_id_t
Definition at line 44 of file eth.h.
typedef uint16_t port_t
Definition at line 49 of file eth.h.
typedef struct socket_connect_info_t socket_connect_info_t
typedef __SOCKET_ID_TYPE__ socket_id_t
Definition at line 46 of file eth.h.
typedef struct socket_t socket_t
Enumeration Type Documentation
enum connect_data_state_t
Enumerator
CONNECT_DATA_STATE_URL
currently there is only a url which needs to be parsed
CONNECT_DATA_STATE_RESOLVE
the hostname is available
CONNECT_DATA_STATE_IPV4
IPv4 and port are ready
CONNECT_DATA_STATE_ERROR
Definition at line 104 of file eth.h.
enum iface_state_t
This enum contains the different interface states
Enumerator
IFACE_STATE_RPC_INTERFACE
interface is a rpc interface, no handling required
IFACE_STATE_UNREGISTERED
interface is not registered
IFACE_STATE_DO_REGISTER
interface is should be registered
IFACE_STATE_STATE_OPERATION_PENDING
interface registering operation in progress
IFACE_STATE_REGISTERED
interface is registered
IFACE_STATE_DO_UNREGISTER
interface should be unregistered
Definition at line 60 of file eth.h.
enum listen_socket_state_t
Enumerator
LISTEN_SOCKET_STATE_CLOSED
LISTEN_SOCKET_STATE_UNUSED
LISTEN_SOCKET_STATE_ACTIVE
Definition at line 87 of file eth.h.
enum send_result_t
Enumerator
SEND_RESULT_OK
SEND_RESULT_CONNECTION_CLOSE
SEND_RESULT_CONNECTION_ERROR
SEND_RESULT_CONNECTION_TIMEOUT
Definition at line 195 of file eth.h.
enum socket_connect_state_t
This defines the state of the data parsing
Enumerator
SOCKET_CONNECT_STATE_URL_SCHEME
State when processing is at URL scheme.
SOCKET_CONNECT_STATE_URL_IPV4_HOSTNAME
State when processing got an IP or till the current char it can be a IP address.
SOCKET_CONNECT_STATE_URI_HOSTNAME
State when processing found out its a hostname.
SOCKET_CONNECT_STATE_URL_IPV6
UNUSED state for IPV6 support ...
SOCKET_CONNECT_STATE_URL_PORT
State when processing the port information.
SOCKET_CONNECT_STATE_CONNECT
State when information can be used to connect.
SOCKET_CONNECT_STATE_ERROR
State when something was not correct.
Definition at line 127 of file eth.h.
enum socket_sig_t
These signals are used to receive information about socket information or to control the socket, or both.
They are used instead of an input or output size.
Enumerator
SOCKET_SIG_COULD_NOT_CONNECT
(In) Could not connect to ip
SOCKET_SIG_COULD_NOT_RESOLVE_HOST
(In) Could not resolve hostname
SOCKET_SIG_RELEASE
SOCKET_SIG_TIMEOUT
(Out) Close socket, release memory<
SOCKET_SIG_CONNECT
(In) Timeout occurred <
SOCKET_SIG_NO_CONNECTION
(Out) Connect socket to connection stored inside additional memory<
SOCKET_SIG_CONNECTED
(In) Socket not connected <
SOCKET_SIG_DATA_SENT
(In) Socket connection established <
SOCKET_SIG_NO_DATA
(In) Data was sent to remote host <
SOCKET_SIG_CLOSE
(In/Out) No data on connection <
Definition at line 315 of file eth.h.
enum socket_state_t
Enumerator
SOCKET_STATE_INACTIVE
socket can be obtained for usage
SOCKET_STATE_SETUP
socket is reserved already and being setup (means it's not called by ros_spin)
SOCKET_STATE_NOT_CONNECTED
socket is not connected
SOCKET_STATE_WAITING_FOR_CONNECTION
socket is currently waiting for a connection
SOCKET_STATE_CONNECTED
socket is connected and able to receive or send data
Definition at line 94 of file eth.h.
Function Documentation
void abstract_close_socket (socket_id_t socket)
Referenced by rosc_spin().
socket_id_t abstract_connect_socket (ip_address_t ip, port_t port)
Connect to a external server by ip and port
Parameters
iface
ip
port
Returns
Referenced by rosc_spin().
bool abstract_get_hostname (char * hostname, size_t maxlength)
Referenced by rosc_init().
bool abstract_resolveIP (const char * hostname, size_t size, ip_address_ptr ip)
This function resolves the IP from a hostname
Parameters
hostname The hostname (NOT TERMINATED BY ZERO!)
size The hostname length
ip[o] The storage for the ip address return false if successfull
Referenced by rosc_hostlist_resolve().
void abstract_ros_spin_routine ()
This routine is exectuted every time ros spin is called.
send_result_t abstract_send_packet (socket_id_t socket_id, uint8_t * buffer, uint32_t size)
This function is from rosc to send out data. It needs to be implemented by the driver or platform package.
Parameters
socket_id the socket_id
buffer the output buffer
size
Returns
result of sending
Referenced by rosc_spin().
socket_id_t abstract_socket_accept (listen_socket_id_t socket_id)
Accept sockets for polling
Referenced by rosc_spin().
socket_id_t abstract_start_listening_on_port (port_t * port)
rosc uses this function to tell the network device to open a port. Normally this function is called by port number 0, for
Parameters
io] port port number
Returns
socket_id or -1 if failed
Referenced by iface_listen().
void abstract_static_initHostname ()
This function initializes the hostname
bool abstract_stop_listening_on_port (socket_id_t socket_id)
rosc uses this function for closing a server port, if the current platform or hardware does not support closing ports, just return PORT_STATUS_UNUSED
Parameters
socket the socket info of the port
Returns
PORT_STATUS_CLOSED or if not supported PORT_STATUS_UNUSED
bool iface_list_insert (iface_t * interface)
Definition at line 137 of file eth.c.
References listen_socket_t::interface, interface_list_start, iface_t::next, and ROSC_ERROR.
Referenced by rosc_init().
void receive_packet (socket_id_t socket_id, uint8_t * buffer, uint32_t size)
This function is called by the driver when something is received on a special socket. It then searches for the socket id inside the socket list and calls the parsing function for that socket. It needs to be called by the driver or platform package when there is data for a specific socket.
Parameters
socket_id
buffer
size
int32_t recv_packet (socket_id_t socket_id, uint8_t * buffer, uint32_t size)
Referenced by rosc_spin().
bool register_interface (iface_t * interface)
Examples:
static_pubsub.c.
Definition at line 169 of file eth.c.
References IFACE_STATE_DO_REGISTER, IFACE_STATE_UNREGISTERED, listen_socket_t::interface, interface_list_start, iface_t::next, and iface_t::state.
bool rosc_hostlist_resolve (const char * hostname, size_t size, ip_address_ptr ip)
This function resolves a hostname, to do this it first uses the built in host list and if the host can not be found there, it uses the abstract resolve command
Parameters
hostname [in] A pointer to the hostname
size the size of the hostname
ip [out] The ip address output
Returns
false if the ip could be obtained
Definition at line 235 of file eth.c.
References abstract_resolveIP(), and rosc_static_lookup_table_size.
Referenced by rosc_spin().
bool rosc_iface_listen (iface_t * iface, uint16_t port_number)
Opens a port for a specific interface
Parameters
iface interface which will use the port
Returns
True if successfull, False if not
void rosc_lists_init ()
Definition at line 58 of file eth.c.
References __LISTENING_SOCKET_MAXIMUM__, __SOCKET_MAXIMUM__, sebs_parser_data_t::additional_storage, socket_t::data, sebs_parser_data_t::handler_data, listen_socket_t::id, socket_t::iface, listen_socket_t::interface, LISTEN_SOCKET_STATE_CLOSED, socket_t::next, listen_socket_t::next, socket_t::pdata, listen_socket_t::port, rosc_static_socket_mem, rosc_static_socket_mem_hdata_offset, rosc_static_socket_mem_message_offset, rosc_static_socket_mem_size, socket_t::state, and listen_socket_t::state.
Referenced by rosc_init().
bool unregister_interface (iface_t * interface)
Definition at line 194 of file eth.c.
References IFACE_STATE_DO_UNREGISTER, IFACE_STATE_REGISTERED, interface_list_start, iface_t::next, and iface_t::state.
Variable Documentation
char hostname[]
Definition at line 39 of file rosc_init.c.
Referenced by msg_gen(), and rosc_init().
iface_t* interface_list_start
Definition at line 48 of file eth.c.
Referenced by iface_list_insert(), iface_list_remove(), register_interface(), rosc_spin(), unregister_interface(), and xmlrpc().
listen_socket_t* listen_socket_list_start
Definition at line 47 of file eth.c.
Referenced by iface_listen(), rosc_spin(), and xmlrpc().
char* const master_uri
Pointer to zero terminated master URI
Referenced by xmlrpc().
char node_name[]
Referenced by msg_gen().
const size_t rosc_static_socket_additional_data_size
Referenced by ros_handler(), and xmlrpc().
socket_t* socket_list_start
Definition at line 46 of file eth.c.
Referenced by publish(), rosc_receive_by_socketid(), rosc_spin(), and xmlrpc().
port_t xmlrpc_port
Definition at line 42 of file rosc_init.c.
Referenced by msg_gen(), and rosc_init().