var annotated =
[
    [ "endian_t", "d9/d6c/structendian__t.html", "d9/d6c/structendian__t" ],
    [ "iface_t", "d5/d64/structiface__t.html", "d5/d64/structiface__t" ],
    [ "listen_socket_t", "d8/dce/structlisten__socket__t.html", "d8/dce/structlisten__socket__t" ],
    [ "lookup_table_entry_t", "dc/d36/structlookup__table__entry__t.html", "dc/d36/structlookup__table__entry__t" ],
    [ "msg_gen_command_t", "dc/ddc/structmsg__gen__command__t.html", "dc/ddc/structmsg__gen__command__t" ],
    [ "msg_gen_handler_init_t", "dc/dbf/structmsg__gen__handler__init__t.html", "dc/dbf/structmsg__gen__handler__init__t" ],
    [ "ros_handler_data_t", "d2/dda/structros__handler__data__t.html", "d2/dda/structros__handler__data__t" ],
    [ "ros_iface_init_t", "d8/d8c/structros__iface__init__t.html", "d8/d8c/structros__iface__init__t" ],
    [ "rosc_msg_submessage_state_t", "d6/de8/structrosc__msg__submessage__state__t.html", "d6/de8/structrosc__msg__submessage__state__t" ],
    [ "sebs_msggen_t", "d2/d57/structsebs__msggen__t.html", "d2/d57/structsebs__msggen__t" ],
    [ "sebs_parse_copy2buffer_data_t", "dc/dd4/structsebs__parse__copy2buffer__data__t.html", "dc/dd4/structsebs__parse__copy2buffer__data__t" ],
    [ "sebs_parse_http_data_t", "db/d79/structsebs__parse__http__data__t.html", "db/d79/structsebs__parse__http__data__t" ],
    [ "sebs_parse_numberparse_data_t", "d3/d0f/structsebs__parse__numberparse__data__t.html", "d3/d0f/structsebs__parse__numberparse__data__t" ],
    [ "sebs_parse_ros_data_t", "de/d95/structsebs__parse__ros__data__t.html", "de/d95/structsebs__parse__ros__data__t" ],
    [ "sebs_parse_seekstring_data_t", "d8/d66/structsebs__parse__seekstring__data__t.html", "d8/d66/structsebs__parse__seekstring__data__t" ],
    [ "sebs_parse_skip_data_t", "d8/d13/structsebs__parse__skip__data__t.html", "d8/d13/structsebs__parse__skip__data__t" ],
    [ "sebs_parse_url_data_t", "d3/d01/structsebs__parse__url__data__t.html", "d3/d01/structsebs__parse__url__data__t" ],
    [ "sebs_parse_xml_data_t", "d9/dbb/structsebs__parse__xml__data__t.html", "d9/dbb/structsebs__parse__xml__data__t" ],
    [ "sebs_parser_call_t", "de/d1c/structsebs__parser__call__t.html", "de/d1c/structsebs__parser__call__t" ],
    [ "sebs_parser_data_t", "dc/d39/structsebs__parser__data__t.html", "dc/d39/structsebs__parser__data__t" ],
    [ "socket_connect_data_t", "de/dc1/structsocket__connect__data__t.html", "de/dc1/structsocket__connect__data__t" ],
    [ "socket_connect_info_t", "d9/d58/structsocket__connect__info__t.html", "d9/d58/structsocket__connect__info__t" ],
    [ "socket_t", "de/d2d/structsocket__t.html", "de/d2d/structsocket__t" ],
    [ "xmlrpc_data_t", "d2/d48/structxmlrpc__data__t.html", "d2/d48/structxmlrpc__data__t" ]
];