SET(ROSC_CORE_SOURCES
src/rosc/msg_parsers/ros_parser.c
src/rosc/msg_parsers/xml_parser.c
src/rosc/msg_parsers/sub/skipwholemessage.c
src/rosc/msg_parsers/sub/seekstring.c
src/rosc/msg_parsers/sub/parseurl.c
src/rosc/msg_parsers/sub/copy2buffer.c
src/rosc/msg_parsers/sub/numberparse.c
src/rosc/msg_parsers/handler/xmlrpc_client.c
src/rosc/msg_parsers/handler/xmlrpc_server.c
src/rosc/msg_parsers/xml_mode/parse_mode_xml.c
src/rosc/msg_parsers/xml_mode/parse_mode_header.c
src/rosc/msg_generators/xml_msg_gen.c
src/rosc/string_res/msg_strings.c
src/rosc/system/system.c
src/rosc/system/rosc_init.c
src/rosc/system/ports.c
src/rosc/system/iface.c
src/rosc/system/endian.c
src/rosc/system/rosc_spin.c
)
