ROSc: src/rosc/com/ros_handler.c File Reference
ros_handler.c File Reference
#include <rosc/system/spec.h>
#include <rosc/com/ros_handler.h>
#include <rosc/debug/debug_out.h>
#include <rosc/system/status.h>
Functions
sebs_parse_return_t ros_handler (sebs_parser_data_t *pdata)
Function Documentation
sebs_parse_return_t ros_handler (sebs_parser_data_t * pdata)
Definition at line 38 of file ros_handler.c.
References sebs_parser_data_t::additional_storage, ros_iface_init_t::array_lengths, ros_iface_init_t::buildup, ros_iface_init_t::callback, sebs_parse_seekstring_data_t::curChrPos, sebs_parser_data_t::current_parser, DEBUG_PRINT, DEBUG_PRINT_STR, sebs_parser_data_t::event, sebs_parse_ros_data_t::field_length, sebs_parser_data_t::function_init, ros_handler_data_t::gen, ros_handler_data_t::genPayloadData, sebs_parser_data_t::handler_data, sebs_parser_data_t::handler_init, ros_handler_data_t::hstate, ros_iface_init_t::iface_name, ros_handler_data_t::iface_ok, sebs_parser_data_t::init_data, sebs_parser_data_t::len, ros_iface_init_t::md5sum, ros_handler_data_t::md5sum_ok, ros_iface_init_t::memory_offsets, ros_iface_init_t::message_definition, sebs_parse_ros_data_t::message_length, MSGGEN_TYPE_ROSMSG_HEADER, sebs_parser_data_t::out_len, sebs_parser_data_t::overall_len, sebs_parser_call_t::parser_data, ros_handler_data_t::publisher_ready, sebs_parse_seekstring_data_t::result, sebs_parser_data_t::return_to_handler, ros_handler_data_t::ros, ros_field_strings, ROS_HANDLER_STATE_CHECK_IFACE_NAME, ROS_HANDLER_STATE_CHECK_MD5SUM, ROS_HANDLER_STATE_NONE, ROS_HANDLER_STATE_SUBSCRIBER_HEADER_SEND, ROS_HANDLER_TYPE_SERVICE_CLIENT, ROS_HANDLER_TYPE_SERVICE_SERVER, ROS_HANDLER_TYPE_TOPIC_PUBLISHER, ROS_HANDLER_TYPE_TOPIC_SUBSCRIBER, ros_iface_init_t::ros_type, ROSC_FATAL, rosc_static_socket_additional_data_size, sebs_parse_ros_data_t::rpc_field_id, SEBS_PARSE_EVENT_LEN_EQUAL_SMALLER_ZERO, SEBS_PARSE_MSG_GEN, SEBS_PARSE_RETURN_GO_AHEAD, SEBS_PARSE_ROS_EVENT_MESSAGE_END, SEBS_PARSE_ROS_EVENT_RPC_FIELD_START, SEBS_PARSE_ROS_INIT_MSG, SEBS_PARSE_ROS_INIT_RPC, SEBS_PARSE_ROS_MODE_BINARY, SEBS_PARSE_ROS_MODE_ROSRPC, SEBS_PARSE_SEEKSTRING_INIT, sebs_parse_ros_data_t::seekstring, sebs_parser_data_t::sending, SOCKET_SIG_CLOSE, SOCKET_SIG_CONNECT, SOCKET_SIG_CONNECTED, SOCKET_SIG_COULD_NOT_CONNECT, SOCKET_SIG_COULD_NOT_RESOLVE_HOST, SOCKET_SIG_DATA_SENT, SOCKET_SIG_NO_CONNECTION, SOCKET_SIG_NO_DATA, SOCKET_SIG_RELEASE, SOCKET_SIG_TIMEOUT, ros_iface_init_t::submessage_sizes, ros_iface_init_t::submessage_states_offset, and ros_iface_init_t::type_name.
Referenced by publish(), publisherfill(), rosc_spin(), and xmlrpc().