ROSc: src/rosc/system/rosc_init.c File Reference
rosc_init.c File Reference
#include <rosc/system/rosc_init.h>
#include <rosc/system/eth.h>
#include <rosc/system/setup.h>
#include <rosc/system/endian.h>
#include <rosc/com/xmlrpc.h>
#include <rosc/com/ros_handler.h>
Functions
void rosc_init ()
Variables
char hostname [__HOSTNAME_MAX_LEN__]
port_t xmlrpc_port =XMLRPC_PORT
Function Documentation
void rosc_init ()
This function initializes a rosc client
Definition at line 55 of file rosc_init.c.
References __HOSTNAME_MAX_LEN__, abstract_get_hostname(), hostname, iface_list_insert(), iface_listen(), rosc_init_endian(), rosc_lists_init(), and xmlrpc_port.
Variable Documentation
char hostname[__HOSTNAME_MAX_LEN__]
Definition at line 39 of file rosc_init.c.
Referenced by msg_gen(), and rosc_init().
port_t xmlrpc_port =XMLRPC_PORT
Definition at line 42 of file rosc_init.c.
Referenced by msg_gen(), and rosc_init().