/*
 * 
 * AUTOGENERATED ROSC MESSAGE HEADER FILE
 * 
 * PACKAGE: examplePackage
 * MESSAGE: exampleMessage
 * MESSAGE CONTENTS: 
 * 
 * uint8[] uint8array
 * 
 *
 * 
 */
#include <rosc.h>

#ifndef ROSC_SYSTEM_HAS_MALLOC
  #ifndef ROSC_examplePackage_uint8array_LENGTH
    #warning 	Included Message Type <exampleMessage> in Package <examplePackage> has a undefined length!\
		According to your settings your System does not support dynamic memory allocation,\
		so you need to define the maximum length with the macro ROSC_examplePackage_uint8array_LENGTH.\
		For this compilation the standart length of STANDARD_UNDEFINED_MSG_LEN is used!\
		If your platform supports memory allocation define ROSC_SYSTEM_HAS_MALLOC.   
  #endif
#endif