ROSc: include/rosc/system/rosc_init.h File Reference
rosc_init.h File Reference
#include <rosc/system/spec.h>
#include <rosc/system/eth.h>
#include <rosc/sebs_parse_fw/sebs_parser_frame.h>
#include <rosc/com/ros_handler.h>
#include <rosc/com/xmlrpc.h>
#include <rosc/system/mem.h>
Macros
#define ROSC_STATIC_SYSTEM_MESSAGE_TYPE_LIST_BEGIN
#define ROSC_STATIC_SYSTEM_MESSAGE_TYPE_LIST_END
#define ROSC_SIZE_LIST_ENTRY_MIN_XMLRPC_OUTPUT_BUFFER(SIZE) char rosc_size_list_min_output_buffer[SIZE];
Functions
void rosc_init ()
Macro Definition Documentation
#define ROSC_SIZE_LIST_ENTRY_MIN_XMLRPC_OUTPUT_BUFFER (SIZE) char rosc_size_list_min_output_buffer[SIZE];
The output buffer of all XMLRPC and ROSRPC services is in total as big as the biggest message size if more performance is required, it might be an option to increase the buffer size (if there is unused memory left) Additionally must be mentioned, that the memory size can even if it's set to 100, can still be a bit larger because of padding bytes of the created structs. Those bytes will be used as output buffer as well.
Examples:
static_pubsub.c.
Definition at line 99 of file rosc_init.h.
#define ROSC_STATIC_SYSTEM_MESSAGE_TYPE_LIST_BEGIN
Value:
typedef struct\
                {\
                        union\
                        {\
                        xmlrpc_data_t xml;\
                        ros_handler_data_t ros;\
                        }handler;\
                        union\
                        {\
                socket_connect_info_t       connect_info;\
                                char connect_string_reservation[offsetof(socket_connect_info_t,url) + __URI_BUFFER_LENGTH__];
STATIC_SYSTEM_MESSAGE_TYPE_LIST_BEGIN defines the begin of the list which must contain all port types on static systems
Examples:
static_pubsub.c.
Definition at line 53 of file rosc_init.h.
#define ROSC_STATIC_SYSTEM_MESSAGE_TYPE_LIST_END
Value:
}message_data;\
                }rosc_socket_memory_size_def_t;\
                \
                const size_t rosc_static_socket_mem_size=sizeof(rosc_socket_memory_size_def_t);\
                rosc_socket_memory_size_def_t rosc_static_socket_mem[__SOCKET_MAXIMUM__];\
                const size_t rosc_static_socket_mem_hdata_offset=offsetof(rosc_socket_memory_size_def_t,handler);\
                const size_t rosc_static_socket_mem_message_offset=offsetof(rosc_socket_memory_size_def_t,message_data);\
                const size_t rosc_static_socket_additional_data_size=sizeof(rosc_socket_memory_size_def_t)-offsetof(rosc_socket_memory_size_def_t,message_data);\
                const size_t rosc_static_url_max_size=sizeof(rosc_socket_memory_size_def_t)-offsetof(rosc_socket_memory_size_def_t,message_data)-offsetof(socket_connect_info_t,url);
STATIC_SYSTEM_MESSAGE_TYPE_LIST_END defines the end of the list which must contain all port types on static systems, it also sets up the necessary external variables for the memory size of all port buffers
Additional information (rosc developers only): We need the type and array size variables here because the port memory size type is not known to rosc functions because it would force the user to have a separate setup header file which needs to be included by all rosc stuff requiring this information. To get arround this, the information is passed by "external" variables, these are setup here.
Examples:
static_pubsub.c.
Definition at line 81 of file rosc_init.h.
Function Documentation
void rosc_init ()
This function initializes a rosc client
Examples:
static_pubsub.c.
Definition at line 55 of file rosc_init.c.
References __HOSTNAME_MAX_LEN__, abstract_get_hostname(), hostname, iface_list_insert(), iface_listen(), rosc_init_endian(), rosc_lists_init(), and xmlrpc_port.