ROSc: include/rosc/com/ros_handler.h File Reference
ros_handler.h File Reference
#include <rosc/sebs_parse_fw/sebs_parser_frame.h>
#include <rosc/sebs_parse_fw/adv_modules/sebs_parse_ros.h>
#include <rosc/com/ros_msg_common.h>
#include <rosc/sebs_parse_fw/send_modules/msggen.h>
#include <rosc/system/eth.h>
Data Structures
struct ros_handler_data_t
Enumerations
enum ros_handler_state {
ROS_HANDLER_STATE_NONE, ROS_HANDLER_STATE_CHECK_MD5SUM, ROS_HANDLER_STATE_CHECK_IFACE_NAME, ROS_HANDLER_STATE_SUBSCRIBER_HEADER_SEND,
ROS_HANDLER_STATE_PUBLISHER_HEADER_SEND
}
Functions
sebs_parse_return_t ros_handler (sebs_parser_data_t *pdata)
void publish (iface_t *interface, void const *msg)
uint32_t publisherfill (iface_t *interface, void const *msg, socket_t *cur)
Enumeration Type Documentation
enum ros_handler_state
Enumerator
ROS_HANDLER_STATE_NONE
ROS_HANDLER_STATE_CHECK_MD5SUM
ROS_HANDLER_STATE_CHECK_IFACE_NAME
ROS_HANDLER_STATE_SUBSCRIBER_HEADER_SEND
ROS_HANDLER_STATE_PUBLISHER_HEADER_SEND
Definition at line 43 of file ros_handler.h.
Function Documentation
void publish (iface_t * interface, void const * msg)
Examples:
static_pubsub.c.
Definition at line 437 of file publish.c.
References sebs_parser_data_t::additional_storage, DEBUG_PRINT_STR, sebs_parser_data_t::handler_data, iface_t::handler_function, socket_t::iface, iface_t::init_data, socket_t::next, sebs_parser_data_t::out_buf, sebs_parser_data_t::out_len, socket_t::pdata, ros_handler_data_t::publisher_ready, publisherfill(), ros_handler(), ROS_HANDLER_TYPE_TOPIC_PUBLISHER, ros_iface_init_t::ros_type, ROSC_FATAL, and socket_list_start.
uint32_t publisherfill (iface_t * interface, void const * msg, socket_t * cur)
Definition at line 36 of file publish.c.
References sebs_parser_data_t::additional_storage, ros_iface_init_t::array_lengths, ros_iface_init_t::buildup, g_byte_order_correction_to_network, iface_t::handler_function, iface_t::init_data, rosc_msg_submessage_state_t::is_dynamic_array, rosc_msg_submessage_state_t::is_submessage_array, ros_iface_init_t::memory_offsets, rosc_msg_submessage_state_t::parent_message_start, socket_t::pdata, ros_handler(), ROS_HANDLER_TYPE_TOPIC_PUBLISHER, ROS_MSG_BUILDUP_TYPE_ARRAY, ROS_MSG_BUILDUP_TYPE_ARRAY_UL, ROS_MSG_BUILDUP_TYPE_BOOL, ROS_MSG_BUILDUP_TYPE_BYTE, ROS_MSG_BUILDUP_TYPE_CHAR, ROS_MSG_BUILDUP_TYPE_DURATION, ROS_MSG_BUILDUP_TYPE_FLOAT32, ROS_MSG_BUILDUP_TYPE_FLOAT64, ROS_MSG_BUILDUP_TYPE_INT16, ROS_MSG_BUILDUP_TYPE_INT32, ROS_MSG_BUILDUP_TYPE_INT64, ROS_MSG_BUILDUP_TYPE_INT8, ROS_MSG_BUILDUP_TYPE_MESSAGE_END, ROS_MSG_BUILDUP_TYPE_STRING, ROS_MSG_BUILDUP_TYPE_SUBMESSAGE, ROS_MSG_BUILDUP_TYPE_SUBMESSAGEARRAY, ROS_MSG_BUILDUP_TYPE_SUBMESSAGEARRAY_UL, ROS_MSG_BUILDUP_TYPE_TIME, ROS_MSG_BUILDUP_TYPE_UINT16, ROS_MSG_BUILDUP_TYPE_UINT32, ROS_MSG_BUILDUP_TYPE_UINT64, ROS_MSG_BUILDUP_TYPE_UINT8, ros_iface_init_t::ros_type, ROSC_FATAL, endian_t::SIZE_2_B, endian_t::SIZE_4_B, endian_t::SIZE_8_B, rosc_msg_submessage_state_t::submessage_array_lengths_start, rosc_msg_submessage_state_t::submessage_buildup_start, rosc_msg_submessage_state_t::submessage_byte_size, rosc_msg_submessage_state_t::submessage_offset_start, ros_iface_init_t::submessage_sizes, ros_iface_init_t::submessage_states_offset, rosc_msg_submessage_state_t::submessage_submessage_size_start, and rosc_msg_submessage_state_t::submessages_remaining.
Referenced by publish().
sebs_parse_return_t ros_handler (sebs_parser_data_t * pdata)
Definition at line 38 of file ros_handler.c.
References sebs_parser_data_t::additional_storage, ros_iface_init_t::array_lengths, ros_iface_init_t::buildup, ros_iface_init_t::callback, sebs_parse_seekstring_data_t::curChrPos, sebs_parser_data_t::current_parser, DEBUG_PRINT, DEBUG_PRINT_STR, sebs_parser_data_t::event, sebs_parse_ros_data_t::field_length, sebs_parser_data_t::function_init, ros_handler_data_t::gen, ros_handler_data_t::genPayloadData, sebs_parser_data_t::handler_data, sebs_parser_data_t::handler_init, ros_handler_data_t::hstate, ros_iface_init_t::iface_name, ros_handler_data_t::iface_ok, sebs_parser_data_t::init_data, sebs_parser_data_t::len, ros_iface_init_t::md5sum, ros_handler_data_t::md5sum_ok, ros_iface_init_t::memory_offsets, ros_iface_init_t::message_definition, sebs_parse_ros_data_t::message_length, MSGGEN_TYPE_ROSMSG_HEADER, sebs_parser_data_t::out_len, sebs_parser_data_t::overall_len, sebs_parser_call_t::parser_data, ros_handler_data_t::publisher_ready, sebs_parse_seekstring_data_t::result, sebs_parser_data_t::return_to_handler, ros_handler_data_t::ros, ros_field_strings, ROS_HANDLER_STATE_CHECK_IFACE_NAME, ROS_HANDLER_STATE_CHECK_MD5SUM, ROS_HANDLER_STATE_NONE, ROS_HANDLER_STATE_SUBSCRIBER_HEADER_SEND, ROS_HANDLER_TYPE_SERVICE_CLIENT, ROS_HANDLER_TYPE_SERVICE_SERVER, ROS_HANDLER_TYPE_TOPIC_PUBLISHER, ROS_HANDLER_TYPE_TOPIC_SUBSCRIBER, ros_iface_init_t::ros_type, ROSC_FATAL, rosc_static_socket_additional_data_size, sebs_parse_ros_data_t::rpc_field_id, SEBS_PARSE_EVENT_LEN_EQUAL_SMALLER_ZERO, SEBS_PARSE_MSG_GEN, SEBS_PARSE_RETURN_GO_AHEAD, SEBS_PARSE_ROS_EVENT_MESSAGE_END, SEBS_PARSE_ROS_EVENT_RPC_FIELD_START, SEBS_PARSE_ROS_INIT_MSG, SEBS_PARSE_ROS_INIT_RPC, SEBS_PARSE_ROS_MODE_BINARY, SEBS_PARSE_ROS_MODE_ROSRPC, SEBS_PARSE_SEEKSTRING_INIT, sebs_parse_ros_data_t::seekstring, sebs_parser_data_t::sending, SOCKET_SIG_CLOSE, SOCKET_SIG_CONNECT, SOCKET_SIG_CONNECTED, SOCKET_SIG_COULD_NOT_CONNECT, SOCKET_SIG_COULD_NOT_RESOLVE_HOST, SOCKET_SIG_DATA_SENT, SOCKET_SIG_NO_CONNECTION, SOCKET_SIG_NO_DATA, SOCKET_SIG_RELEASE, SOCKET_SIG_TIMEOUT, ros_iface_init_t::submessage_sizes, ros_iface_init_t::submessage_states_offset, and ros_iface_init_t::type_name.
Referenced by publish(), publisherfill(), rosc_spin(), and xmlrpc().