ROSc: src/rosc/com/publish.c File Reference
publish.c File Reference
#include <rosc/com/ros_handler.h>
#include <rosc/system/endian.h>
#include <string.h>
Functions
uint32_t publisherfill (iface_t *interface, void const *msg, socket_t *cur)
void publish (iface_t *interface, void const *msg)
Function Documentation
void publish (iface_t * interface, void const * msg)
Definition at line 437 of file publish.c.
References sebs_parser_data_t::additional_storage, DEBUG_PRINT_STR, sebs_parser_data_t::handler_data, iface_t::handler_function, socket_t::iface, iface_t::init_data, socket_t::next, sebs_parser_data_t::out_buf, sebs_parser_data_t::out_len, socket_t::pdata, ros_handler_data_t::publisher_ready, publisherfill(), ros_handler(), ROS_HANDLER_TYPE_TOPIC_PUBLISHER, ros_iface_init_t::ros_type, ROSC_FATAL, and socket_list_start.
uint32_t publisherfill (iface_t * interface, void const * msg, socket_t * cur)
Definition at line 36 of file publish.c.
References sebs_parser_data_t::additional_storage, ros_iface_init_t::array_lengths, ros_iface_init_t::buildup, g_byte_order_correction_to_network, iface_t::handler_function, iface_t::init_data, rosc_msg_submessage_state_t::is_dynamic_array, rosc_msg_submessage_state_t::is_submessage_array, ros_iface_init_t::memory_offsets, rosc_msg_submessage_state_t::parent_message_start, socket_t::pdata, ros_handler(), ROS_HANDLER_TYPE_TOPIC_PUBLISHER, ROS_MSG_BUILDUP_TYPE_ARRAY, ROS_MSG_BUILDUP_TYPE_ARRAY_UL, ROS_MSG_BUILDUP_TYPE_BOOL, ROS_MSG_BUILDUP_TYPE_BYTE, ROS_MSG_BUILDUP_TYPE_CHAR, ROS_MSG_BUILDUP_TYPE_DURATION, ROS_MSG_BUILDUP_TYPE_FLOAT32, ROS_MSG_BUILDUP_TYPE_FLOAT64, ROS_MSG_BUILDUP_TYPE_INT16, ROS_MSG_BUILDUP_TYPE_INT32, ROS_MSG_BUILDUP_TYPE_INT64, ROS_MSG_BUILDUP_TYPE_INT8, ROS_MSG_BUILDUP_TYPE_MESSAGE_END, ROS_MSG_BUILDUP_TYPE_STRING, ROS_MSG_BUILDUP_TYPE_SUBMESSAGE, ROS_MSG_BUILDUP_TYPE_SUBMESSAGEARRAY, ROS_MSG_BUILDUP_TYPE_SUBMESSAGEARRAY_UL, ROS_MSG_BUILDUP_TYPE_TIME, ROS_MSG_BUILDUP_TYPE_UINT16, ROS_MSG_BUILDUP_TYPE_UINT32, ROS_MSG_BUILDUP_TYPE_UINT64, ROS_MSG_BUILDUP_TYPE_UINT8, ros_iface_init_t::ros_type, ROSC_FATAL, endian_t::SIZE_2_B, endian_t::SIZE_4_B, endian_t::SIZE_8_B, rosc_msg_submessage_state_t::submessage_array_lengths_start, rosc_msg_submessage_state_t::submessage_buildup_start, rosc_msg_submessage_state_t::submessage_byte_size, rosc_msg_submessage_state_t::submessage_offset_start, ros_iface_init_t::submessage_sizes, ros_iface_init_t::submessage_states_offset, rosc_msg_submessage_state_t::submessage_submessage_size_start, and rosc_msg_submessage_state_t::submessages_remaining.
Referenced by publish().