ROSc: endian_t Struct Reference
endian_t Struct Reference
#include <endian.h>
Data Fields
union {
uint16_t SIZE_2
int8_t SIZE_2_B [sizeof(uint16_t)]
};
union {
uint32_t SIZE_4
int8_t SIZE_4_B [sizeof(uint32_t)]
};
union {
uint64_t SIZE_8
int8_t SIZE_8_B [sizeof(uint64_t)]
};
Detailed Description
This type of the struct stores the byte order for each common type of the system, when the values are initialized with like for example 0x0807060504030201 for 8 bytes.
Definition at line 46 of file endian.h.
Field Documentation
union { ... }
union { ... }
union { ... }
uint16_t endian_t::SIZE_2
Definition at line 50 of file endian.h.
int8_t endian_t::SIZE_2_B[sizeof(uint16_t)]
Definition at line 51 of file endian.h.
Referenced by msg_gen(), publisherfill(), rosc_init_endian(), and sebs_parse_ros().
uint32_t endian_t::SIZE_4
Definition at line 55 of file endian.h.
int8_t endian_t::SIZE_4_B[sizeof(uint32_t)]
Definition at line 56 of file endian.h.
Referenced by msg_gen(), publisherfill(), rosc_init_endian(), and sebs_parse_ros().
uint64_t endian_t::SIZE_8
Definition at line 60 of file endian.h.
int8_t endian_t::SIZE_8_B[sizeof(uint64_t)]
Definition at line 61 of file endian.h.
Referenced by msg_gen(), publisherfill(), rosc_init_endian(), and sebs_parse_ros().
The documentation for this struct was generated from the following file:
include/rosc/system/endian.h