#Integer
int8 tbi_int8
int16 tbi_int16
int32 tbi_int32
int64 tbi_int64

#Unsigned Integer
uint8 tbi_uint8
uint16 tbi_uint16
uint32 tbi_uint32
uint64 tbi_uint64

#Float
float32 tbi_float32
float64 tbi_float64

#Bool
bool tbi_bool

#String
string tbi_string

#Time
time tbi_time

#Duration
duration tbi_duration

#Integer
int8[] tbi_int8_A
int16[2] tbi_int16_A
int32[] tbi_int32_A
int64[] tbi_int64_A

#Unsigned Integer
uint8[] tbi_uint8_A
uint16[] tbi_uint16_A
uint32[2] tbi_uint32_A
uint64[] tbi_uint64_A

#Float
float32[2] tbi_float32_A
float64[] tbi_float64_A

#Bool
bool[] tbi_bool_A

#String
string[] tbi_string_A

#Time
time[2] tbi_time_A

#Duration
duration[] tbi_duration_A

test_submessage t_nbi_sub
test_submessage[] t_nbi_sub_A
