My Project: src/rosxmosNode.c File Reference
src/rosxmosNode.c File Reference
#include "rosxmosNode.h"
Functions
void str2buf (unsigned int *index, char *buffer, char *str, char mode)
void generateHeader (char *message_buffer, http_head_gen_command *gen_array, char **custom_string_array, unsigned int *buf_index)
char generateXML (char *message_buffer, ros_rpc_gen_command *gen_array, char **custom_string_array, unsigned int *gen_index, unsigned int *buf_index)
Variables
char * ros_rpc_tag_strings [15]
char * ros_rpc_stdtext [20]
char * http_header_descriptors [18]
char * http_header_stdtext [22]
Function Documentation
void generateHeader (char * message_buffer, http_head_gen_command * gen_array, char ** custom_string_array, unsigned int * buf_index)
This function can be used to generate headers for a HTTP message.
Parameters:
[out] message_buffer The output buffer for the message
[in] gen_array The command array for generating messages.
[in] custom_string_array The array for custom strings
buf_index The index for the output buffer
Returns:
Message length
Definition at line 124 of file rosxmosNode.c.
References HTTP_HEADER_DESC_BEGIN, http_header_descriptors, HTTP_HEADER_GEN_DESC_CUSTOM, HTTP_HEADER_GEN_END, HTTP_HEADER_GEN_VAL_CUSTOM, http_header_stdtext, HTTP_HEADER_VALUE_BEGIN, S2B_HTTP_HEAD_FIELD, S2B_HTTP_HEAD_FIELD_DESC, and str2buf().
Referenced by main().
char generateXML (char * message_buffer, ros_rpc_gen_command * gen_array, char ** custom_string_array, unsigned int * gen_index, unsigned int * buf_index)
This function generates a xmlrpc message
Parameters:
[out] message_buffer The output buffer for the message
[in] gen_array The command array for generating messages.
[in] custom_string_array The array for custom strings (topics, params etc.)
gen_index The index for the gen_array, set to 0 at start, increased by each call of generate_XML
buf_index The index for the output buffer
Returns:
Message length
Definition at line 149 of file rosxmosNode.c.
References GEN_ERROR, GEN_LEVEL_UP, GEN_RETURN_GO_AHEAD, GEN_STOP, generateXML(), ros_rpc_stdtext, ros_rpc_tag_strings, RPC_CLOSE_TAG, RPC_CUSTOM_TAG, RPC_CUSTOM_TEXT, RPC_GENERATOR_FINISH, RPC_STDTEXT_START, RPC_TAG_START, RPC_XML_DECLARATION, S2B_CTAG, S2B_NORMAL, S2B_TAG, and str2buf().
Referenced by generateXML().
void str2buf (unsigned int * index, char * buffer, char * str, char mode)
This function copies a string into a buffer. The starting point inside the string is given with the index pointer, which is also increased. This is used to be able to add multiple strings behind each other in the same buffer. Be sure your buffer is big enough, there are no checks for the buffer size for increasing performance!
Parameters:
index The current index
buffer The buffer to write the string to.
str The terminated string to write into the buffer
mode This specifies the mode, see str2buf_modes enum
Definition at line 73 of file rosxmosNode.c.
References S2B_CTAG, S2B_HTTP_HEAD_FIELD, S2B_HTTP_HEAD_FIELD_DESC, and S2B_TAG.
Referenced by generateHeader(), and generateXML().
Variable Documentation
char* http_header_descriptors[18]
Initial value:
{
                "Server",
                "User-Agent",
                "Date",
                "Host",
                "Content-Type",
                "Content-length",
                "Accepted-Encoding"
}
This array contains the strings for standard fields in the message headers Note to editors: If you add something here make sure its also available (in the SAME ORDER) in the http_head_gen_command enum command block (for numbers>=HTTP_HEADER_DESC_BEGIN)
Definition at line 44 of file rosxmosNode.c.
Referenced by generateHeader().
char* http_header_stdtext[22]
Initial value:
{
                "POST / HTTP/1.1",
                "XMLRPC ROSc-NodeLib",
                "BaseHTTP/ROSc-NodeLib",
                "text/xml",
                "HTTP/1.0",
                "OK"
}
This array contains the standard value strings for generating message headers Note to editors: If you add something here make sure its also available (in the SAME ORDER) in the http_head_gen_command enum command block (for numbers>=HTTP_HEADER_VALUE_BEGIN)
Definition at line 60 of file rosxmosNode.c.
Referenced by generateHeader().
char* ros_rpc_stdtext[20]
Initial value:
{
        "hasParam",
        "registerPublisher",
        "registerSubscriber",
        "requestTopic",
        "tcp_keepalive",
        "unregisterPublisher",
        "unregisterSubscriber"
}
This array contains the strings for standard tags. Note to editors: If you add something here make sure its also available (in the SAME ORDER) in the ros_rpc_gen_command enum command block (for numbers>4000) (make it alphabetically ordered, maybe necessary!)
Definition at line 28 of file rosxmosNode.c.
Referenced by generateXML().
char* ros_rpc_tag_strings[15]
Initial value:
{
        "array",
        "boolean",
        "data",
        "int",
        "methodcall",
        "methodname",
        "methodresponse",
        "param",
        "params",
        "string",
        "value"
}
This array contains the strings for standard tags. Note to editors: If you add something here make sure its also available (in the SAME ORDER) in the ros_rpc_gen_command enum command block (for numbers>2000) (make it alphabetically ordered, maybe necessary!)
Definition at line 8 of file rosxmosNode.c.
Referenced by generateXML().