My Project: src/rosxmosNode.h File Reference
src/rosxmosNode.h File Reference
#include <stdio.h>
#include <string.h>
#include <stdbool.h>
Data Structures
struct ros_node_setup
Defines
#define RPC_TAG_START 100
#define RPC_STDTEXT_START 150
#define HTTP_HEADER_DESC_BEGIN 50
#define HTTP_HEADER_VALUE_BEGIN 150
Enumerations
enum ros_rpc_gen_command {
RPC_CLOSE_TAG = 0, RPC_GENERATOR_FINISH, RPC_XML_DECLARATION, RPC_TAG_ARRAY = RPC_TAG_START,
RPC_TAG_BOOLEAN, RPC_TAG_DATA, RPC_TAG_INT, RPC_TAG_METHODCALL,
RPC_TAG_METHODNAME, RPC_TAG_METHODRESPONSE, RPC_TAG_PARAM, RPC_TAG_PARAMS,
RPC_TAG_STRING, RPC_TAG_VALUE, RPC_CUSTOM_TAG, RPC_STDTEXT_HASPARAM = RPC_STDTEXT_START,
RPC_STDTEXT_REGISTERPUBLISHER, RPC_STDTEXT_REGISTERSUBSCRIBER, RPC_STDTEXT_REQUESTTOPIC, RPC_STDTEXT_TCP_KEEPALIVE,
RPC_STDTEXT_UNREGISTERPUBLISHER, RPC_STDTEXT_UNREGISTERSUBSCRIBER, RPC_CUSTOM_TEXT
}
enum http_head_gen_command {
HTTP_HEADER_GEN_END = 0, HTTP_HEADER_GEN_DESC_SERVER = HTTP_HEADER_DESC_BEGIN, HTTP_HEADER_GEN_DESC_USER_AGENT, HTTP_HEADER_GEN_DESC_DATE,
HTTP_HEADER_GEN_DESC_HOST, HTTP_HEADER_GEN_DESC_CONTENT_TYPE, HTTP_HEADER_GEN_DESC_CONTENT_LENGTH, HTTP_HEADER_GEN_DESC_ACCEPTED_CODING,
HTTP_HEADER_GEN_DESC_CUSTOM, HTTP_HEADER_GEN_VAL_POST_HTTP_1_1 = HTTP_HEADER_VALUE_BEGIN, HTTP_HEADER_GEN_VAL_XMLRPC_ROSC_NODELIB, HTTP_HEADER_GEN_VAL_BASEHTTP_ROSC_NODELIB,
HTTP_HEADER_GEN_VAL_TEXT_XML, HTTP_HEADER_GEN_VAL_HTTP_1_0, HTTP_HEADER_GEN_VAL_OK, HTTP_HEADER_GEN_VAL_CUSTOM
}
enum ros_rpc_gen_return { GEN_RETURN_GO_AHEAD = 0, GEN_LEVEL_UP, GEN_STOP, GEN_ERROR }
enum str2buf_modes {
S2B_NORMAL = 0, S2B_TAG, S2B_CTAG, S2B_HTTP_HEAD_FIELD_DESC,
S2B_HTTP_HEAD_FIELD
}
Functions
void str2buf (unsigned int *index, char *buffer, char *str, char mode)
void generateHeader (char *message_buffer, http_head_gen_command *gen_array, char **custom_string_array, unsigned int *buf_index)
char generateXML (char *message_buffer, ros_rpc_gen_command *gen_array, char **custom_string_array, unsigned int *gen_index, unsigned int *buf_index)
Define Documentation
#define HTTP_HEADER_DESC_BEGIN 50
Command enum for the xmlrpc message generator
Definition at line 88 of file rosxmosNode.h.
Referenced by generateHeader().
#define HTTP_HEADER_VALUE_BEGIN 150
Definition at line 89 of file rosxmosNode.h.
Referenced by generateHeader().
#define RPC_STDTEXT_START 150
Definition at line 30 of file rosxmosNode.h.
Referenced by generateXML().
#define RPC_TAG_START 100
Command enum for the xmlrpc message generator
Definition at line 29 of file rosxmosNode.h.
Referenced by generateXML().
Enumeration Type Documentation
enum http_head_gen_command
Enumerator:
HTTP_HEADER_GEN_END
This is required on any header generation array end.
HTTP_HEADER_GEN_DESC_SERVER
Values specifying most used standard field descriptors
HTTP_HEADER_GEN_DESC_USER_AGENT
HTTP_HEADER_GEN_DESC_DATE
HTTP_HEADER_GEN_DESC_HOST
HTTP_HEADER_GEN_DESC_CONTENT_TYPE
HTTP_HEADER_GEN_DESC_CONTENT_LENGTH
HTTP_HEADER_GEN_DESC_ACCEPTED_CODING
HTTP_HEADER_GEN_DESC_CUSTOM
This specifies to use a text in the custom text array as descriptor
HTTP_HEADER_GEN_VAL_POST_HTTP_1_1
Values specifying most used standard text pieces
HTTP_HEADER_GEN_VAL_XMLRPC_ROSC_NODELIB
HTTP_HEADER_GEN_VAL_BASEHTTP_ROSC_NODELIB
HTTP_HEADER_GEN_VAL_TEXT_XML
HTTP_HEADER_GEN_VAL_HTTP_1_0
HTTP_HEADER_GEN_VAL_OK
HTTP_HEADER_GEN_VAL_CUSTOM
This specifies to use a text in the custom text array as value
Definition at line 91 of file rosxmosNode.h.
enum ros_rpc_gen_command
This enum holds the commands for the rpc XML generator
Enumerator:
RPC_CLOSE_TAG
Close current tag.
RPC_GENERATOR_FINISH
Stops the generator at any place.
RPC_XML_DECLARATION
Places XML Declaration.
RPC_TAG_ARRAY
place tag array
RPC_TAG_BOOLEAN
place tag boolean
RPC_TAG_DATA
place tag data
RPC_TAG_INT
place tag int
RPC_TAG_METHODCALL
place tag methodcall
RPC_TAG_METHODNAME
place tag methodname
RPC_TAG_METHODRESPONSE
place tag methodresponse
RPC_TAG_PARAM
place tag param
RPC_TAG_PARAMS
place tag params
RPC_TAG_STRING
place tag string
RPC_TAG_VALUE
place tag value
RPC_CUSTOM_TAG
RPC_CUSTOM_TAG.
Use this number for selecting custom tag strings where RPC_CUSTOM_TAG is the first (0) string of your custom array and RPC_CUSTOM_TAG+X, tag X in your array
RPC_STDTEXT_HASPARAM
place text "hasParam" in the current open tag
RPC_STDTEXT_REGISTERPUBLISHER
place text "registerPublisher" in the current open tag
RPC_STDTEXT_REGISTERSUBSCRIBER
place text "registerSubscriber" in the current open tag
RPC_STDTEXT_REQUESTTOPIC
place text "requestTopic" in the current open tag
RPC_STDTEXT_TCP_KEEPALIVE
place text "tcp_keepalive" in the current open tag
RPC_STDTEXT_UNREGISTERPUBLISHER
place text "unregisterPublisher" in the current open tag
RPC_STDTEXT_UNREGISTERSUBSCRIBER
place text "unregisterSubscriber" in the current open tag
RPC_CUSTOM_TEXT
RPC_CUSTOM_TEXT.
Use this number for selecting custom text strings where RPC_CUSTOM_TEXT is the first (0) string of your custom array and RPC_CUSTOM_TAG+X, tag X in your array
Definition at line 37 of file rosxmosNode.h.
enum ros_rpc_gen_return
Return values of the __generateXML function
Enumerator:
GEN_RETURN_GO_AHEAD
GEN_LEVEL_UP
GEN_STOP
GEN_ERROR
Definition at line 135 of file rosxmosNode.h.
enum str2buf_modes
These are the modes for the str2buf function
Enumerator:
S2B_NORMAL
This mode does just insert the given string.
S2B_TAG
This mode will insert the string with tag brackets.
S2B_CTAG
This mode will insert the string as closing tag.
S2B_HTTP_HEAD_FIELD_DESC
This mode adds a : to the string.
S2B_HTTP_HEAD_FIELD
This mode adds a space infront and a newline at the back of the string.
Definition at line 147 of file rosxmosNode.h.
Function Documentation
void generateHeader (char * message_buffer, http_head_gen_command * gen_array, char ** custom_string_array, unsigned int * buf_index)
This function can be used to generate headers for a HTTP message.
Parameters:
[out] message_buffer The output buffer for the message
[in] gen_array The command array for generating messages.
[in] custom_string_array The array for custom strings
buf_index The index for the output buffer
Returns:
Message length
Definition at line 124 of file rosxmosNode.c.
References HTTP_HEADER_DESC_BEGIN, http_header_descriptors, HTTP_HEADER_GEN_DESC_CUSTOM, HTTP_HEADER_GEN_END, HTTP_HEADER_GEN_VAL_CUSTOM, http_header_stdtext, HTTP_HEADER_VALUE_BEGIN, S2B_HTTP_HEAD_FIELD, S2B_HTTP_HEAD_FIELD_DESC, and str2buf().
Referenced by main().
char generateXML (char * message_buffer, ros_rpc_gen_command * gen_array, char ** custom_string_array, unsigned int * gen_index, unsigned int * buf_index)
This function generates a xmlrpc message
Parameters:
[out] message_buffer The output buffer for the message
[in] gen_array The command array for generating messages.
[in] custom_string_array The array for custom strings (topics, params etc.)
gen_index The index for the gen_array, set to 0 at start, increased by each call of generate_XML
buf_index The index for the output buffer
Returns:
Message length
Definition at line 149 of file rosxmosNode.c.
References GEN_ERROR, GEN_LEVEL_UP, GEN_RETURN_GO_AHEAD, GEN_STOP, generateXML(), ros_rpc_stdtext, ros_rpc_tag_strings, RPC_CLOSE_TAG, RPC_CUSTOM_TAG, RPC_CUSTOM_TEXT, RPC_GENERATOR_FINISH, RPC_STDTEXT_START, RPC_TAG_START, RPC_XML_DECLARATION, S2B_CTAG, S2B_NORMAL, S2B_TAG, and str2buf().
Referenced by generateXML().
void str2buf (unsigned int * index, char * buffer, char * str, char mode)
This function copies a string into a buffer. The starting point inside the string is given with the index pointer, which is also increased. This is used to be able to add multiple strings behind each other in the same buffer. Be sure your buffer is big enough, there are no checks for the buffer size for increasing performance!
Parameters:
index The current index
buffer The buffer to write the string to.
str The terminated string to write into the buffer
mode This specifies the mode, see str2buf_modes enum
Definition at line 73 of file rosxmosNode.c.
References S2B_CTAG, S2B_HTTP_HEAD_FIELD, S2B_HTTP_HEAD_FIELD_DESC, and S2B_TAG.
Referenced by generateHeader(), and generateXML().