ROSc: include/rosc/system/rosc_spin.h File Reference
rosc_spin.h File Reference
Functions
void rosc_spin ()
Function Documentation
void rosc_spin ()
Todo:
port reservation for xmlrpc
Examples:
static_subscriber.c.
Definition at line 42 of file rosc_spin.c.
References abstract_close_socket(), abstract_connect_socket(), abstract_send_packet(), abstract_socket_accept(), xmlrpc_data_t::client_type, CONNECT_DATA_STATE_IPV4, CONNECT_DATA_STATE_RESOLVE, socket_t::connect_info, sebs_parser_data_t::connection_interface, socket_connect_info_t::data_state, DEBUG_PRINT_STR, sebs_parser_data_t::handler_data, iface_t::handler_function, sebs_parser_data_t::handler_function, sebs_parser_data_t::handler_init, socket_connect_info_t::hostname, socket_connect_info_t::hostname_size, listen_socket_t::id, socket_t::iface, IFACE_STATE_DO_REGISTER, IFACE_STATE_DO_UNREGISTER, IFACE_STATE_STATE_OPERATION_PENDING, iface_t::init_data, sebs_parser_data_t::init_data, listen_socket_t::interface, interface_list_start, listen_socket_list_start, iface_t::next, socket_t::next, listen_socket_t::next, sebs_parser_data_t::out_buf, sebs_parser_data_t::out_len, socket_t::pdata, recv_packet(), socket_connect_info_t::remote_ip, socket_connect_info_t::remote_port, socket_t::reserved, ros_handler(), rosc_hostlist_resolve(), sebs_parser_frame(), SEND_RESULT_OK, socket_t::socket_id, socket_list_start, SOCKET_SIG_CLOSE, SOCKET_SIG_CONNECT, SOCKET_SIG_CONNECTED, SOCKET_SIG_COULD_NOT_CONNECT, SOCKET_SIG_COULD_NOT_RESOLVE_HOST, SOCKET_SIG_DATA_SENT, SOCKET_SIG_NO_CONNECTION, SOCKET_SIG_NO_DATA, SOCKET_SIG_RELEASE, SOCKET_STATE_CONNECTED, SOCKET_STATE_INACTIVE, SOCKET_STATE_NOT_CONNECTED, SOCKET_STATE_WAITING_FOR_CONNECTION, iface_t::state, socket_t::state, xmlrpc(), XMLRPC_CLIENT_TYPE_REGISTER, and XMLRPC_CLIENT_TYPE_UNREGISTER.