#ifndef PARSE_XML_H_
#define PARSE_XML_H_

#include <rosc/string_res/msg_strings.h>

/**
 * This enum contains the state for the xml definition check
 */
typedef enum
{
	XML_DEF_SEEK_LT, //!< XML_DEF_SEEK_LT means that parser is currently searching for "<"
	XML_DEF_SEEK_QM0,//!< XML_DEF_SEEK_QM0 means that parser awaits a question mark as next char
	XML_DEF_SEEK_X,  //!< XML_DEF_SEEK_X means that parser awaits a x now
	XML_DEF_SEEK_M,  //!< XML_DEF_SEEK_M means that parser awaits a m now
	XML_DEF_SEEK_L,  //!< XML_DEF_SEEK_L means that parser awaits a l now
	XML_DEF_SEEK_QM1,//!< XML_DEF_SEEK_QM1 means that parser awaits another ? now ignoring all other chars inside the def tag
	XML_DEF_SEEK_GT, //!< XML_DEF_SEEK_GT means that parser awaits ">"
	XML_PARSE,       //!< XML_PARSE means that the parser is currently parsing XML
	XML_PARSE_INSIDE_TAG, //!< XML_PARSE_INSIDE_TAG means that the parser is parsing XML an currently inside a tag definition
}parse_xml_state_t;

/**
 * This enum contains the number for each known tag
 */
typedef enum
{
	__RPC_XML_TAG_STRINGS(XML) //!< imports all string numbers from autogenerated file
}parse_xml_tags_t;

#endif /* PARSE_XML_H_ */
